### ISSUE TITLE
The curser is off 

### ISSUE THREAD

**Issue by demoncode-cyber** [xSute/Osu-Sleeky#3]
When I see replay player the curser seems like it is going the right way but it is in the wrong position I tried with multiple replays it did the same thing I have my sensitivity on 1x so could you help me with this problem.

**Comment by xSute** [comment]
> When I see replay player the curser seems like it is going the right way but it is in the wrong position I tried with multiple replays it did the same thing I have my sensitivity on 1x so could you help me with this problem.

You might have the wrong mods on, or You might have "Flip replay" on which would explain the issue.
